/** Editorial companions, not replacements for the source chapters or evidence grades. */
export interface LearningGuide {
  slug: string;
  meaning: string;
  translation: string;
  example: string;
  tinyAction: string;
  caution: string;
  question: string;
  answer: string;
  planId: string;
}

export const LEARNING_GUIDES: LearningGuide[] = [
  {
    slug: "belief-engineers-reality",
    meaning: "What you expect can change what you attempt. Test an assumption through a small action, then look at what actually happened.",
    translation: "The belief loop means expectation → action → feedback. It does not mean thoughts control outside events.",
    example: "Instead of ‘I cannot learn maths’, try one worked example, then solve a similar question and check the answer.",
    tinyAction: "In two minutes, write one assumption and one safe way to test it today.",
    caution: "A mindset study is not a promise of a particular health, academic or career outcome.",
    question: "You expect to fail a presentation. What would test that belief?",
    answer: "Practise the opening with one person and ask what was clear. Use the feedback, not your prediction alone.",
    planId: "belief-test",
  },
  {
    slug: "power-of-delusion",
    meaning: "An ambitious possibility can be worth testing before you feel confident. Keep checking it against evidence.",
    translation: "‘Delusion’ here is a provocative label for provisional confidence, not a recommendation to ignore reality.",
    example: "A first-time applicant drafts one portfolio example and asks for feedback instead of assuming nobody will hire them.",
    tinyAction: "Write one ‘I could try…’ sentence and a two-minute first move.",
    caution: "A success story does not establish what everyone can achieve. Change course when the evidence calls for it.",
    question: "What separates useful confidence from refusing feedback?",
    answer: "Useful confidence leads to a test and an honest review, including evidence that the idea needs changing.",
    planId: "belief-test",
  },
  {
    slug: "every-version-of-you-exists",
    meaning: "Choose a quality you want to practise, then express it in one specific behaviour.",
    translation: "‘Versions’ and ‘collapse’ are metaphors for choosing and acting, not claims about quantum physics or parallel lives.",
    example: "‘A prepared student’ becomes opening tomorrow’s notes and writing one question tonight.",
    tinyAction: "Finish: ‘Tomorrow, after ___, I will ___ for two minutes.’",
    caution: "Imagining an identity is not the same as practising a skill, and a missed action does not define you.",
    question: "How would you turn ‘I am organised’ into something observable?",
    answer: "Choose a concrete action, such as putting the materials for tomorrow’s class in one place.",
    planId: "tiny-start",
  },
  {
    slug: "the-backwards-equation",
    meaning: "Describe a finish you can recognise, work backwards to a few milestones, then choose the next action.",
    translation: "The ‘equation’ is a planning tool, not a mathematical guarantee that a set of inputs produces success.",
    example: "Submit an essay Friday → draft Thursday → outline Wednesday → write three headings now.",
    tinyAction: "Write the finish and just three milestones. You do not need a 20-step plan to begin.",
    caution: "Dates and milestones are estimates. Revise them when constraints or feedback change.",
    question: "What is missing from ‘get better at coding’?",
    answer: "A visible result and a next action: for example, build one working form, beginning with its first input.",
    planId: "reverse-plan",
  },
  {
    slug: "the-manifestation-quadrant",
    meaning: "Connect what you want, what you assume, what you do and the feedback you receive.",
    translation: "‘Signal’, ‘amplifier’, ‘bridge’ and ‘mirror’ mean goal, belief, action and observed response.",
    example: "You want clearer meetings, assume nobody listens, try sending an agenda, then ask whether it helped.",
    tinyAction: "Write four short lines: want / assumption / next action / what I will observe.",
    caution: "Other people and circumstances are not mirrors you can control. Results do not prove your thoughts caused them.",
    question: "If your action gets no response, what should you review?",
    answer: "The approach, context and assumptions. Silence alone does not tell you which one caused the result.",
    planId: "belief-test",
  },
  {
    slug: "the-unseen-architecture",
    meaning: "Some results arrive later than the effort. Track the work and the outcome separately, with a date to reassess.",
    translation: "‘Compression’ and the ‘J-curve’ describe a possible delay, not a law that every plateau ends in a breakthrough.",
    example: "Track practice questions attempted and errors understood each week, alongside later test performance.",
    tinyAction: "Pick one action to count, one result to watch and a review date.",
    caution: "A flat result can mean waiting, changing the method or stopping. Persistence alone does not prove a strategy works.",
    question: "What makes waiting different from staying stuck indefinitely?",
    answer: "A review date and criteria for changing the approach, rather than assuming a payoff must arrive.",
    planId: "weekly-review",
  },
  {
    slug: "the-ancient-technique",
    meaning: "Rehearse the steps of an upcoming action, then practise them in the real setting.",
    translation: "Process rehearsal means imagining what you will do, not only picturing the result you want.",
    example: "Before a call, rehearse your opening sentence and how you will ask one clear question.",
    tinyAction: "Spend two minutes imagining or writing the first three steps of tomorrow’s task.",
    caution: "Rehearsal is optional and does not replace practice. A written checklist is a valid alternative to visual imagery.",
    question: "Which rehearsal is more actionable: applause or your opening sentence?",
    answer: "Your opening sentence, because it gives you a behaviour to practise and improve.",
    planId: "rehearse",
  },
  {
    slug: "the-identity-stack",
    meaning: "Build a useful self-description from repeatable actions rather than waiting to feel like a different person.",
    translation: "An ‘identity vote’ is simply one action consistent with a quality you value.",
    example: "‘I am someone who learns’ becomes reviewing one mistake after a practice exercise.",
    tinyAction: "Choose one verb—write, practise, listen—and make its smallest version take two minutes.",
    caution: "Rest and missed days do not erase your identity. A minimum is adjustable, not a test of personal worth.",
    question: "You miss your small habit. What does that say about who you are?",
    answer: "One missed action is information about the situation, not a verdict on your identity. Adjust the next attempt.",
    planId: "tiny-start",
  },
  {
    slug: "the-borrowed-state",
    meaning: "Borrow a specific behaviour from someone you admire to help you begin a difficult situation.",
    translation: "A ‘borrowed state’ can be a slower speaking pace or a prepared opening, not becoming another person.",
    example: "Before asking a question in class, rehearse a calm first sentence in your own words.",
    tinyAction: "Choose one useful behaviour and practise it for 30 seconds.",
    caution: "A posture is not a guaranteed biological switch. Use an approach that feels comfortable and authentic.",
    question: "What could you borrow without copying someone’s personality?",
    answer: "A concrete technique, such as pausing before answering or bringing three prepared questions.",
    planId: "rehearse",
  },
  {
    slug: "the-purpose-antidote",
    meaning: "You can explore direction through a small useful project without settling your life’s purpose first.",
    translation: "A ‘mission’ can be a provisional experiment in what interests you or helps someone else.",
    example: "Spend a week making one helpful study sheet for a classmate, then decide whether you want to continue.",
    tinyAction: "List one curiosity and one person or problem you would like to help.",
    caution: "Feeling low is not proof of lacking purpose. This exercise is not mental-health treatment.",
    question: "Do you need a permanent life mission to choose a useful next step?",
    answer: "No. Try a small, reversible project and use what you learn to choose the next one.",
    planId: "seven-day-trial",
  },
  {
    slug: "the-wanting-trap",
    meaning: "Give one optional priority your attention for now, while keeping other possibilities somewhere you can revisit.",
    translation: "‘The vacuum’ means reducing competing demands; it is not a force that attracts outcomes.",
    example: "Finish one portfolio page this week. Keep the podcast and new course on a later list.",
    tinyAction: "Sort three optional projects into Now, Next and Later.",
    caution: "Essential responsibilities do not disappear when you choose a focus. Financial or time constraints are real.",
    question: "What should happen to a good idea you cannot take on now?",
    answer: "Park it with a review date rather than treating every new idea as today’s obligation.",
    planId: "morning-plan",
  },
  {
    slug: "effortless-achievement",
    meaning: "Make the task clear, remove one avoidable interruption and choose a manageable stretch of work.",
    translation: "‘Laminar work’ means less task-switching. LIGHTEN / LEVEL / LEAN means simplify / match difficulty / begin.",
    example: "Instead of ‘study all afternoon’, work on three practice questions with messages muted for one short block.",
    tinyAction: "Name one output and close one unrelated tab.",
    caution: "Good conditions do not guarantee flow. Start smaller than 90 minutes if that fits your day.",
    question: "You finish a block without feeling ‘in flow’. Was it wasted?",
    answer: "Not necessarily. Look at the work and what you learned, not whether a special feeling appeared.",
    planId: "pomodoro",
  },
  {
    slug: "hate-your-life-correctly",
    meaning: "Name a situation you want to change without turning it into an attack on yourself.",
    translation: "Despite the title, the practical move is compassionate problem-solving, not self-hatred.",
    example: "‘I am useless’ becomes ‘I missed the deadline; I need to ask for a revised date and reduce the scope.’",
    tinyAction: "Rewrite one harsh judgement as a neutral description of what happened.",
    caution: "You do not need distress to earn change. Rest, support and professional help can matter more than another productivity task.",
    question: "How would you respond if a friend made the same mistake?",
    answer: "Use that same fair tone with yourself, then identify one controllable step or source of support.",
    planId: "two-lines",
  },
  {
    slug: "the-unified-life",
    meaning: "Plan focused work alongside your needs and responsibilities, rather than treating them as competing identities.",
    translation: "‘Floors’ are adjustable minimum supports; ‘one life’ means planning the whole week, not just work.",
    example: "Place caring responsibilities and rest in the calendar before choosing two realistic project sessions.",
    tinyAction: "Protect one important responsibility and find one realistic work slot.",
    caution: "A fixed 80/20 split will not fit every life. Capacity, access needs and unexpected events can change the plan.",
    question: "What should you change when the plan repeatedly exceeds your capacity?",
    answer: "Reduce or rearrange the plan. Do not treat an unrealistic schedule as a character failure.",
    planId: "seven-day-trial",
  },
  {
    slug: "the-two-lines",
    meaning: "Evaluate your results without using them to measure your worth as a person.",
    translation: "The ‘orange line’ is changing performance; the ‘green line’ is the respect you owe yourself regardless.",
    example: "An exam mark tells you which material needs work. It does not establish how worthy you are.",
    tinyAction: "Write one outcome as a fact, then one kind and useful response.",
    caution: "Self-respect is not another technique you must perform perfectly to get better results.",
    question: "What can a disappointing result tell you—and what can it not tell you?",
    answer: "It can offer feedback about this attempt. It cannot measure your human worth.",
    planId: "two-lines",
  },
  {
    slug: "the-high-frequency-human",
    meaning: "Notice which parts of your day support or drain your available energy, then make one manageable adjustment.",
    translation: "‘Frequency’ is an energy-budget metaphor, not a measurable vibration or a ranking of people.",
    example: "Notice that consecutive meetings leave no transition time; try a short buffer before the next task.",
    tinyAction: "Write one support, one drain and one small change within your control.",
    caution: "Fatigue is not a moral failure. Persistent health concerns need appropriate care, not only habit changes.",
    question: "What is a more useful question than ‘Why am I low-frequency?’",
    answer: "‘What is affecting my capacity today, and what support or adjustment is available?’",
    planId: "energy-check",
  },
  {
    slug: "stop-overthinking",
    meaning: "For a low-stakes, reversible choice, set a limit on deliberation and learn from a small trial.",
    translation: "‘70% information’ is a rough prompt to stop chasing certainty, not a threshold you can measure precisely.",
    example: "Try one note-taking layout for a week instead of comparing apps for another evening.",
    tinyAction: "Name the choice, two options and how you would undo it.",
    caution: "Do not apply a quick-decision rule to high-stakes medical, legal, financial or safety decisions.",
    question: "Which choice suits a short timebox: a notebook layout or signing a major contract?",
    answer: "The notebook layout. A consequential commitment can require more information and qualified advice.",
    planId: "decision",
  },
  {
    slug: "unbreakable-discipline",
    meaning: "Make the desired action easier to begin and reduce one source of friction.",
    translation: "‘Environment design’ means changing the setup, such as leaving the right file open, rather than demanding more willpower.",
    example: "Put the practice worksheet on your desk and start with its first question.",
    tinyAction: "Prepare one tool and do the first two minutes of the task.",
    caution: "‘Unbreakable’ is not a realistic standard. Rest, illness and interruptions call for adjustment, not punishment.",
    question: "If the task keeps getting delayed, what could you change besides trying harder?",
    answer: "Shrink the first action, choose a better cue or remove a practical obstacle.",
    planId: "tiny-start",
  },
  {
    slug: "mastering-motivation",
    meaning: "Try a small action before waiting for the perfect mood, then decide whether continuing is useful.",
    translation: "‘Action before motivation’ is an experiment, not a promise that starting always changes how you feel.",
    example: "Write one rough sentence. After two minutes, choose to continue, change the task or stop.",
    tinyAction: "Choose a two-minute action you genuinely want to try.",
    caution: "Low motivation can have many causes. Persistent difficulty is not proof that you are choosing badly.",
    question: "You start but still feel unmotivated. What options remain?",
    answer: "Continue if useful, reduce the task, rest or seek support. The experiment has not measured your worth.",
    planId: "tiny-start",
  },
  {
    slug: "boredom-tolerance",
    meaning: "Practise a brief pause before an automatic distraction so you can choose what to do next.",
    translation: "The ‘ladder’ means gradually trying a longer pause if helpful—not forcing yourself through distress.",
    example: "Before opening a feed, wait ten seconds and ask whether you need information, connection or a break.",
    tinyAction: "At the next phone impulse, pause for ten seconds, then make a deliberate choice.",
    caution: "This is not a dopamine reset or treatment. Sensory supports and necessary communication do not need to be removed.",
    question: "Is choosing to use your phone after the pause automatically a failure?",
    answer: "No. The purpose is a more deliberate choice, which may include using the phone for a real need.",
    planId: "pause",
  },
  {
    slug: "god-mode",
    meaning: "Protect a work period with one output, a simple setup and a short review.",
    translation: "‘God mode’ is a name for a structured focus session, not an exceptional state you must achieve.",
    example: "Draft the introduction, keep a distraction note beside you and finish by recording the next step.",
    tinyAction: "Define one visible output small enough for a 10- or 25-minute attempt.",
    caution: "A 60–90-minute block is optional. Longer is not automatically better, and interruptions may be unavoidable.",
    question: "What should be clear before the timer starts?",
    answer: "What you will work on and what progress would look like, even if the whole task is not finished.",
    planId: "pomodoro",
  },
  {
    slug: "the-one-hour-law",
    meaning: "Give one skill repeated attention through learning, trying and explaining—not only consuming information.",
    translation: "The ‘law’ is a suggested routine, not a scientific rule requiring exactly one hour every day.",
    example: "Read one coding example, modify it yourself, then explain why the change worked.",
    tinyAction: "Choose one small skill and write a question you want to be able to answer.",
    caution: "Use the time you have. A shorter session with feedback is a valid starting point.",
    question: "How could you tell whether a tutorial taught you something usable?",
    answer: "Try a related task without copying and explain your decisions. Check any gaps against the source.",
    planId: "learn-practise",
  },
  {
    slug: "consistency-and-procrastination",
    meaning: "Make returning easier after a missed session. Learn from the obstacle without creating a punishment backlog.",
    translation: "A ‘comeback rep’ is a small restart, not repayment for every minute you missed.",
    example: "After missing Tuesday, open the draft on Wednesday and add one heading before replanning.",
    tinyAction: "Name the obstacle and choose a two-minute restart or a realistic new time.",
    caution: "‘Never miss twice’ is a cue, not a rule for illness, emergencies or recovery. Rest can be the right choice.",
    question: "What should a restart plan optimise for?",
    answer: "Making the next useful action possible—not guilt, catching up at any cost or protecting a perfect streak.",
    planId: "tiny-start",
  },
  {
    slug: "hyperfocus",
    meaning: "Work on one defined output for a bounded period, park distractions and take a real break.",
    translation: "An ‘attention lock’ is a practical setup, not a demand for uninterrupted concentration.",
    example: "Attempt three revision questions, note unrelated thoughts, then take a break before reviewing errors.",
    tinyAction: "Write your next output and put a blank distraction note beside it.",
    caution: "Focus intervals are adjustable. Necessary interruptions are not failures, and a timer cannot verify concentration.",
    question: "What can you do when an unrelated task comes to mind mid-session?",
    answer: "Note it for later, then return if appropriate. If it is urgent or essential, stop and handle it.",
    planId: "pomodoro",
  },
  {
    slug: "the-one-daily-habit",
    meaning: "Finish one clearly bounded action and notice what you did before adding more commitments.",
    translation: "The ‘winner’s loop’ means choose / attempt / acknowledge, not win every day or keep extending the session.",
    example: "Edit one paragraph, record that change and leave a note about where to resume.",
    tinyAction: "Choose an output that fits two minutes and define what ‘done’ means.",
    caution: "There is no obligation to progress to 90 minutes. A quiet written acknowledgement works as well as saying ‘done’ aloud.",
    question: "What is a better daily action than ‘work on my project’?",
    answer: "An observable unit such as ‘draft three headings’ or ‘test one function’ with an achievable finish.",
    planId: "morning-plan",
  },
  {
    slug: "the-productivity-glitch",
    meaning: "Check whether organising work has displaced doing it. Pause one unnecessary layer and try a simpler setup.",
    translation: "‘Subtraction’ means removing avoidable overhead, not deleting every tool or blaming yourself.",
    example: "For one session, use the existing task list instead of rebuilding the entire dashboard.",
    tinyAction: "Name one optional organising task you can postpone until after the real task.",
    caution: "Keep accessibility aids, essential reminders and backups. Try reversible changes before deleting tools or data.",
    question: "How would you test whether a new system is helping?",
    answer: "Compare the useful work and overhead during a small trial, while preserving anything you need to function safely.",
    planId: "decision",
  },
  {
    slug: "one-week-vs-twelve-months",
    meaning: "Use a short planning cycle to make a realistic commitment, review what happened and adjust.",
    translation: "A ‘weekly initiative’ is one visible result for this week, not a miniature plan for every area of life.",
    example: "Plan three small portfolio sessions, leave buffer time and review the actual draft at the end of the week.",
    tinyAction: "Choose one weekly output and the first realistic session for it.",
    caution: "A weekly rhythm is an option, not a compounding guarantee. Reduce commitments when circumstances change.",
    question: "What belongs in a useful weekly review besides a completion count?",
    answer: "What changed, what got in the way and one adjustment to the next plan.",
    planId: "seven-day-trial",
  },
  {
    slug: "the-24-hour-empire",
    meaning: "Turn a business idea into a small test of a specific problem before investing heavily in a complete launch.",
    translation: "‘Empire’ and ‘24 hours’ describe ambition and a timebox, not evidence that a viable business can be guaranteed in a day.",
    example: "Draft a one-page description of a study-planning service and ask a willing potential user what they actually need.",
    tinyAction: "Write who the idea is for, what problem you think they have and what you still need to learn.",
    caution: "Do not treat a pricing formula or success story as financial advice. Payments and publishing require separate checks.",
    question: "What would you learn from a person saying the idea sounds nice?",
    answer: "It is a starting reaction, not proof of demand. Ask about their real problem and current approach without pressuring them.",
    planId: "seven-day-trial",
  },
];

export function getLearningGuide(slug: string) {
  return LEARNING_GUIDES.find((guide) => guide.slug === slug);
}
