"use client";

import { useMemo, useState, useSyncExternalStore } from "react";
import Link from "next/link";
import { AlertCircle, BookOpen, Check, Clock3, MessageCircle, Play, Sparkles } from "lucide-react";
import type { Chapter, SearchDoc } from "@/lib/types";
import { aiSourceLabel } from "@/lib/ai/contracts";
import type { AiContext, AiSource, CoachResult, ContentReference, TutorResult } from "@/lib/ai/contracts";
import { chapterReference } from "@/lib/ai/context";
import { retrieveLevelUpContent } from "@/lib/ai/retrieval";
import { createAiServices } from "@/lib/ai/services";
import { validateCoachRequest, validatePlannerRequest, validateTutorRequest } from "@/lib/ai/schemas";
import {
  OLLAMA_MODEL,
  checkOllamaStatus,
  configuredOllamaEndpoint,
  type OllamaStatus,
} from "@/lib/ai/ollama-provider";
import { saveAiPlan, setAiSessionStatus, useAiPlanStore } from "@/lib/ai/store";
import { WEBGPU_MODEL, startWebGpuModel } from "@/lib/ai/webgpu-provider";
import {
  WEBGPU_PROVISION_SERVER,
  cancelWebGpuDownload,
  getWebGpuProvisionState,
  subscribeWebGpuProvision,
  type WebGpuProvisionState,
} from "@/lib/ai/webgpu-provision";

interface AiStudyPanelProps {
  context: AiContext;
  documents: SearchDoc[];
  chapters: Chapter[];
}

type BusyOperation = "planner" | "coach" | "tutor" | null;

const buttonClass = "inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-gold px-4 py-2 text-sm font-semibold text-paper transition-colors hover:bg-gold-deep focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gold disabled:cursor-not-allowed disabled:opacity-50";
const secondaryButtonClass = "inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-line bg-paper-deep px-3 py-2 text-sm font-medium text-ink-soft transition-colors hover:border-gold hover:text-gold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gold disabled:cursor-not-allowed disabled:opacity-50";

function TypePill({ type }: { type: string }) {
  return <span className="rounded-full border border-line bg-paper-deep px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-ink-faint">{type}</span>;
}

function ResultSource({ source, note, fallbackReason }: { source: AiSource; note?: string; fallbackReason?: string }) {
  const fallbackNote = fallbackReason === "ollama-unavailable"
    ? "Ollama was unavailable, so this answer was generated by the deterministic fallback."
    : fallbackReason === "no-ollama"
      ? "Ollama is not available, so this answer was generated by the deterministic fallback."
      : "This answer was generated locally from your saved LevelUp state.";
  return (
    <div className="mt-3 rounded-lg border border-line/80 bg-paper-deep/60 px-3 py-2 text-xs text-ink-soft" role="status" aria-live="polite">
      <span className="font-semibold text-ink">{aiSourceLabel(source)}.</span>{" "}
      {note ?? fallbackNote}
    </div>
  );
}

function OllamaStatusCard({ status, checking, onCheck }: { status: OllamaStatus; checking: boolean; onCheck: () => void }) {
  const label = checking
    ? "Checking local AI…"
    : status.state === "not-checked"
      ? "Not checked yet"
      : status.state === "ready"
      ? "Local AI ready"
      : status.state === "model-missing"
        ? "Install the local model"
        : status.state === "blocked"
          ? "Local-only AI enforced"
          : "Using deterministic fallback";
  return (
    <div className="mt-5 rounded-xl border border-line bg-paper-deep/70 p-4" role="status" aria-live="polite">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-gold">Local AI status</p>
          <p className="mt-1 text-sm font-semibold text-ink">{label}</p>
          <p className="mt-1 max-w-2xl text-xs leading-relaxed text-ink-soft">
            {checking ? "Checking the Ollama app on this device." : status.message} Locked to <code className="rounded border border-line px-1">{OLLAMA_MODEL}</code>. No prompt, response, or saved study data is sent to LevelUp analytics or a remote AI service.
          </p>
        </div>
        <button type="button" onClick={onCheck} disabled={checking} className={secondaryButtonClass}>
          {checking ? "Checking…" : "Check again"}
        </button>
      </div>
      <p className="mt-3 text-[11px] leading-relaxed text-ink-faint">
        Public visitors cannot use this computer&apos;s Ollama. Anyone who wants model-powered help must install Ollama and run this locked model on their own device; the deterministic Coach, Planner, and Tutor work without it.
      </p>
    </div>
  );
}

function WebGpuCard({ provision }: { provision: WebGpuProvisionState }) {
  const [starting, setStarting] = useState(false);

  async function start() {
    setStarting(true);
    await startWebGpuModel();
    setStarting(false);
  }

  if (!provision.available) return null;

  const isIdle = provision.status === "idle" || provision.status === "cancelled";
  const working = starting || provision.status === "downloading";

  return (
    <div className="mt-5 rounded-xl border border-line bg-paper-deep/70 p-4" role="status" aria-live="polite">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-gold">In-browser AI engine</p>
            <span className="rounded-full border border-line bg-paper-deep px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-ink-faint">webgpu engine</span>
          </div>
          {isIdle ? (
            <>
              <p className="mt-1 text-sm font-semibold text-ink">
                {provision.status === "cancelled" ? "Download cancelled" : "Run the AI directly on this device"}
              </p>
              <p className="mt-1 max-w-2xl text-xs leading-relaxed text-ink-soft">
                {provision.status === "cancelled"
                  ? "The download stopped. Your question is still answered by the other engines."
                  : "A small in-browser model (~1 GB) answers Coach, Planner, and Tutor on this device. Everything runs locally; nothing is sent to a remote AI service."}{" "}
                Locked to <code className="rounded border border-line px-1">{WEBGPU_MODEL}</code>.
              </p>
            </>
          ) : null}
          {provision.status === "downloading" ? (
            <>
              <p className="mt-1 text-sm font-semibold text-ink">Downloading the in-browser model</p>
              <p className="mt-1 max-w-2xl truncate text-xs leading-relaxed text-ink-soft">{provision.text || "Downloading…"}</p>
              <div className="mt-3 flex items-center gap-2">
                <div className="h-2 w-56 max-w-full overflow-hidden rounded-full bg-line" role="progressbar" aria-valuenow={Math.round(provision.progress * 100)} aria-valuemin={0} aria-valuemax={100}>
                  <div className="h-full rounded-full bg-gold" style={{ width: `${Math.round(provision.progress * 100)}%` }}></div>
                </div>
                <span className="text-xs font-semibold text-ink">{Math.round(provision.progress * 100)}%</span>
              </div>
            </>
          ) : null}
          {provision.status === "ready" ? (
            <>
              <p className="mt-1 text-sm font-semibold text-ink">In-browser model ready</p>
              <p className="mt-1 max-w-2xl text-xs leading-relaxed text-ink-soft">
                {provision.text} Coach, Planner, and Tutor prefer this engine when it is ready.
              </p>
            </>
          ) : null}
          {provision.status === "error" && provision.error ? (
            <>
              <p className="mt-1 text-sm font-semibold text-ink">The in-browser model could not start</p>
              <p className="mt-1 max-w-2xl text-xs leading-relaxed text-ink-soft">{provision.error.message}</p>
            </>
          ) : null}
        </div>
        <div className="flex flex-wrap gap-2">
          <button type="button" onClick={() => void start()} disabled={working || provision.status === "ready"} className={provision.status === "idle" ? buttonClass : secondaryButtonClass}>
            {working
              ? "Downloading…"
              : provision.status === "ready"
                ? "Ready"
                : provision.status === "cancelled"
                  ? "Try again"
                  : "Download the in-browser model"}
          </button>
          {provision.status === "downloading" ? (
            <button type="button" onClick={cancelWebGpuDownload} className={secondaryButtonClass}>
              Cancel download
            </button>
          ) : null}
        </div>
      </div>
    </div>
  );
}

function ErrorMessage({ message }: { message: string }) {
  return (
    <div className="mt-3 flex items-start gap-2 rounded-lg border border-rose/30 bg-rose/5 px-3 py-2 text-sm text-ink" role="alert">
      <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-rose" aria-hidden="true" />
      <span>{message}</span>
    </div>
  );
}

export default function AiStudyPanel({ context, documents, chapters }: AiStudyPanelProps) {
  const planState = useAiPlanStore();
  const plan = planState.plans[context.date] ?? null;
  const services = useMemo(() => createAiServices(), []);
  const webGpu = useSyncExternalStore(subscribeWebGpuProvision, getWebGpuProvisionState, () => WEBGPU_PROVISION_SERVER);
  const defaultChapter = context.progress.nextChapterSlug ?? chapters[0]?.slug ?? "";
  const [availableMinutes, setAvailableMinutes] = useState(String(context.profile.preferredMinutesPerDay || 30));
  const [objective, setObjective] = useState("");
  const [question, setQuestion] = useState("");
  const [coach, setCoach] = useState<CoachResult | null>(null);
  const [coachMeta, setCoachMeta] = useState<{ source: AiSource; note?: string; fallbackReason?: string } | null>(null);
  const [tutor, setTutor] = useState<TutorResult | null>(null);
  const [tutorMeta, setTutorMeta] = useState<{ source: AiSource; note?: string; fallbackReason?: string } | null>(null);
  const [tutorChapter, setTutorChapter] = useState(defaultChapter);
  const [tutorMode, setTutorMode] = useState<"explain" | "summarize" | "practice">("explain");
  const [tutorLevel, setTutorLevel] = useState<"beginner" | "normal" | "advanced">("normal");
  const [busy, setBusy] = useState<BusyOperation>(null);
  const [error, setError] = useState<string | null>(null);
  const [ollamaStatus, setOllamaStatus] = useState<OllamaStatus>({ state: "not-checked", message: "Choose Check again to see whether Ollama is ready on this device." });
  const [checkingOllama, setCheckingOllama] = useState(false);

  const selectedChapter = chapters.find((chapter) => chapter.slug === tutorChapter) ?? null;

  async function refreshOllamaStatus() {
    setCheckingOllama(true);
    setOllamaStatus(await checkOllamaStatus({ endpoint: configuredOllamaEndpoint() }));
    setCheckingOllama(false);
  }

  async function generatePlan() {
    const request = validatePlannerRequest({ date: context.date, availableMinutes: Number(availableMinutes), objective: objective || undefined });
    if (!request) {
      setError("Choose between 5 and 240 minutes. The objective is optional and should be brief.");
      return;
    }
    setBusy("planner");
    setError(null);
    const refs = retrieveLevelUpContent(documents, `${request.objective ?? "today"} ${context.mission.label} ${context.profile.weakSubjects.join(" ")}`, 4);
    const result = await services.planner(request, context, refs);
    setBusy(null);
    if (!result.ok) {
      setError(result.error.message);
      return;
    }
    saveAiPlan(result.value);
  }

  async function askCoach(event?: React.FormEvent) {
    event?.preventDefault();
    const request = validateCoachRequest({ question });
    if (!request) {
      setError("Ask a short question so the Coach can give you a specific next move.");
      return;
    }
    setBusy("coach");
    setError(null);
    const refs = retrieveLevelUpContent(documents, request.question, 4);
    const result = await services.coach(request, context, refs);
    setBusy(null);
    if (!result.ok) {
      setError(result.error.message);
      return;
    }
    setCoach(result.value);
    setCoachMeta({ source: result.source, note: result.note, fallbackReason: result.fallbackReason });
  }

  async function runTutor() {
    const request = validateTutorRequest({ chapterSlug: tutorChapter, mode: tutorMode, level: tutorLevel });
    if (!request || !selectedChapter) {
      setError("Choose a LevelUp chapter before starting the Tutor.");
      return;
    }
    setBusy("tutor");
    setError(null);
    const refs: ContentReference[] = [chapterReference(selectedChapter), ...retrieveLevelUpContent(documents, `${selectedChapter.title} ${selectedChapter.keyConcepts.join(" ")}`, 3)];
    const uniqueRefs = refs.filter((ref, index) => refs.findIndex((candidate) => candidate.id === ref.id) === index);
    const result = await services.tutor(request, context, uniqueRefs);
    setBusy(null);
    if (!result.ok) {
      setError(result.error.message);
      return;
    }
    setTutor(result.value);
    setTutorMeta({ source: result.source, note: result.note, fallbackReason: result.fallbackReason });
  }

  function updateSession(date: string, sessionId: string, status: "started" | "completed") {
    setAiSessionStatus(date, sessionId, status);
  }

  return (
    <section className="rounded-2xl border border-line bg-card p-6 shadow-xs sm:p-8" aria-labelledby="ai-study-heading">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="max-w-2xl">
          <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-gold">
            <Sparkles className="h-4 w-4" aria-hidden="true" />
            LevelUp Coach
          </div>
          <h2 id="ai-study-heading" className="mt-2 font-display text-2xl font-bold tracking-tight text-ink">Turn today into a next move</h2>
          <p className="mt-2 text-sm leading-relaxed text-ink-soft">
            Plans, answers, and explanations use the progress already on this device. Ollama is optional and runs only on the computer using this page; if it is unavailable, the deterministic fallback still works.
          </p>
        </div>
        <span className="rounded-full border border-line bg-paper-deep px-3 py-1 text-[11px] font-semibold uppercase tracking-wider text-ink-faint">
          Local-only AI
        </span>
      </div>

      <OllamaStatusCard status={ollamaStatus} checking={checkingOllama} onCheck={() => void refreshOllamaStatus()} />

      <WebGpuCard provision={webGpu} />

      <div className="mt-6 grid gap-5 lg:grid-cols-2">
        <div className="rounded-xl border border-line bg-paper p-5">
          <div className="flex items-start justify-between gap-3">
            <div>
              <p className="font-display text-xs font-semibold uppercase tracking-[0.18em] text-gold">Daily Planner</p>
              <h3 className="mt-1 font-display text-lg font-semibold text-ink">Generate today&apos;s plan</h3>
            </div>
            <Clock3 className="h-5 w-5 text-ink-faint" aria-hidden="true" />
          </div>
          <div className="mt-4 grid gap-3 sm:grid-cols-[120px_1fr]">
            <label className="block">
              <span className="text-xs font-medium text-ink-soft">Minutes</span>
              <input
                type="number"
                min={5}
                max={240}
                step={5}
                value={availableMinutes}
                onChange={(event) => setAvailableMinutes(event.target.value)}
                className="mt-1 w-full rounded-lg border border-line bg-card px-3 py-2 text-sm text-ink focus:border-gold focus:outline-none focus-visible:ring-2 focus-visible:ring-gold/40"
              />
            </label>
            <label className="block">
              <span className="text-xs font-medium text-ink-soft">Objective <span className="text-ink-faint">(optional)</span></span>
              <input
                type="text"
                maxLength={240}
                value={objective}
                onChange={(event) => setObjective(event.target.value)}
                placeholder={context.mission.label}
                className="mt-1 w-full rounded-lg border border-line bg-card px-3 py-2 text-sm text-ink placeholder:text-ink-faint focus:border-gold focus:outline-none focus-visible:ring-2 focus-visible:ring-gold/40"
              />
            </label>
          </div>
          <button type="button" onClick={generatePlan} disabled={busy !== null} className={`mt-4 w-full ${buttonClass}`}>
            <Sparkles className="h-4 w-4" aria-hidden="true" />
            {busy === "planner" ? "Building a plan…" : "Generate today’s plan"}
          </button>

          {plan ? (
            <div className="mt-5 border-t border-line pt-4">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wider text-ink-faint">{plan.priority}</p>
                  <p className="mt-1 font-display text-base font-semibold text-ink">{plan.objective}</p>
                </div>
                <TypePill type={aiSourceLabel(plan.source)} />
              </div>
              <ol className="mt-4 space-y-3">
                {plan.sessions.map((session) => (
                  <li key={session.id} className="rounded-lg border border-line bg-card p-3">
                    <div className="flex items-start gap-3">
                      <div className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-line text-gold" aria-hidden="true">
                        {session.status === "completed" ? <Check className="h-4 w-4" /> : <span className="font-mono text-xs">{session.durationMinutes}</span>}
                      </div>
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <h4 className="font-medium text-ink">{session.title}</h4>
                          <TypePill type={session.type} />
                        </div>
                        <p className="mt-1 text-xs leading-relaxed text-ink-soft">{session.reason}</p>
                        {session.chapterSlug ? <Link href={`/chapters/${session.chapterSlug}/`} className="mt-2 inline-flex min-h-8 items-center gap-1 text-xs font-semibold text-gold hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gold"><BookOpen className="h-3 w-3" aria-hidden="true" />Open chapter</Link> : null}
                        <div className="mt-3 flex flex-wrap gap-2">
                          {session.status === "pending" ? <button type="button" onClick={() => updateSession(plan.date, session.id, "started")} className={secondaryButtonClass}><Play className="h-3.5 w-3.5" aria-hidden="true" />Start</button> : null}
                          {session.status === "started" ? <button type="button" onClick={() => updateSession(plan.date, session.id, "completed")} className={buttonClass}><Check className="h-3.5 w-3.5" aria-hidden="true" />Complete</button> : null}
                          {session.status === "completed" ? <span className="inline-flex min-h-8 items-center gap-1 text-xs font-semibold text-gold"><Check className="h-3.5 w-3.5" aria-hidden="true" />Completed</span> : null}
                        </div>
                      </div>
                    </div>
                  </li>
                ))}
              </ol>
              <ResultSource source={plan.source} />
            </div>
          ) : (
            <p className="mt-4 text-xs leading-relaxed text-ink-faint">No plan is saved for today yet. Generate one when you are ready to choose the next move.</p>
          )}
        </div>

        <div className="space-y-5">
          <div className="rounded-xl border border-line bg-paper p-5">
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="font-display text-xs font-semibold uppercase tracking-[0.18em] text-gold">Ask Coach</p>
                <h3 className="mt-1 font-display text-lg font-semibold text-ink">What should happen next?</h3>
              </div>
              <MessageCircle className="h-5 w-5 text-ink-faint" aria-hidden="true" />
            </div>
            <div className="mt-3 flex flex-wrap gap-2">
              {["What should I focus on today?", "What should I learn next?", "Why am I falling behind?"].map((prompt) => (
                <button key={prompt} type="button" onClick={() => setQuestion(prompt)} className="min-h-9 rounded-full border border-line bg-card px-3 py-1.5 text-xs text-ink-soft transition-colors hover:border-gold hover:text-gold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gold">{prompt}</button>
              ))}
            </div>
            <form className="mt-3" onSubmit={askCoach}>
              <label htmlFor="coach-question" className="sr-only">Ask the LevelUp Coach</label>
              <textarea id="coach-question" maxLength={500} rows={3} value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about today, recovery, progress, or what to learn next." className="w-full resize-y rounded-lg border border-line bg-card px-3 py-2 text-sm text-ink placeholder:text-ink-faint focus:border-gold focus:outline-none focus-visible:ring-2 focus-visible:ring-gold/40" />
              <button type="submit" disabled={busy !== null} className={`mt-3 ${buttonClass}`}>
                <MessageCircle className="h-4 w-4" aria-hidden="true" />
                {busy === "coach" ? "Thinking…" : "Ask Coach"}
              </button>
            </form>
            {coach ? <div className="mt-4 border-t border-line pt-4"><p className="text-sm leading-relaxed text-ink">{coach.answer}</p><ul className="mt-3 space-y-1.5 text-xs text-ink-soft">{coach.nextActions.map((action) => <li key={action} className="flex gap-2"><span className="text-gold">→</span><span>{action}</span></li>)}</ul><p className="mt-3 text-[11px] text-ink-faint">Basis: {coach.basis.join(" · ")}</p>{coachMeta ? <ResultSource source={coachMeta.source} note={coachMeta.note} fallbackReason={coachMeta.fallbackReason} /> : null}</div> : null}
          </div>

          <div className="rounded-xl border border-line bg-paper p-5">
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="font-display text-xs font-semibold uppercase tracking-[0.18em] text-gold">Tutor</p>
                <h3 className="mt-1 font-display text-lg font-semibold text-ink">Explain or practice a chapter</h3>
              </div>
              <BookOpen className="h-5 w-5 text-ink-faint" aria-hidden="true" />
            </div>
            <div className="mt-4 grid gap-3 sm:grid-cols-3">
              <label className="block sm:col-span-3">
                <span className="text-xs font-medium text-ink-soft">Chapter</span>
                <select value={tutorChapter} onChange={(event) => setTutorChapter(event.target.value)} className="mt-1 w-full rounded-lg border border-line bg-card px-3 py-2 text-sm text-ink focus:border-gold focus:outline-none focus-visible:ring-2 focus-visible:ring-gold/40">
                  {chapters.map((chapter) => <option key={chapter.slug} value={chapter.slug}>Chapter {chapter.number} — {chapter.title}</option>)}
                </select>
              </label>
              <label className="block"><span className="text-xs font-medium text-ink-soft">Mode</span><select value={tutorMode} onChange={(event) => setTutorMode(event.target.value as typeof tutorMode)} className="mt-1 w-full rounded-lg border border-line bg-card px-3 py-2 text-sm text-ink focus:border-gold focus:outline-none focus-visible:ring-2 focus-visible:ring-gold/40"><option value="explain">Explain</option><option value="summarize">Summarize</option><option value="practice">Practice</option></select></label>
              <label className="block"><span className="text-xs font-medium text-ink-soft">Level</span><select value={tutorLevel} onChange={(event) => setTutorLevel(event.target.value as typeof tutorLevel)} className="mt-1 w-full rounded-lg border border-line bg-card px-3 py-2 text-sm text-ink focus:border-gold focus:outline-none focus-visible:ring-2 focus-visible:ring-gold/40"><option value="beginner">Beginner</option><option value="normal">Normal</option><option value="advanced">Advanced</option></select></label>
              <div className="flex items-end"><button type="button" onClick={runTutor} disabled={busy !== null || chapters.length === 0} className={`w-full ${buttonClass}`}>{busy === "tutor" ? "Preparing…" : "Start Tutor"}</button></div>
            </div>
            {tutor ? <div className="mt-4 border-t border-line pt-4"><p className="text-sm leading-relaxed text-ink">{tutor.answer}</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-wider text-ink-faint">Takeaways</p><ul className="mt-2 space-y-1 text-xs text-ink-soft">{tutor.takeaways.map((item) => <li key={item}>• {item}</li>)}</ul></div><div><p className="text-xs font-semibold uppercase tracking-wider text-ink-faint">Try this</p><ul className="mt-2 space-y-1 text-xs text-ink-soft">{tutor.practicePrompts.map((item) => <li key={item}>• {item}</li>)}</ul></div></div><p className="mt-3 text-[11px] text-ink-faint">{tutor.evidenceNote}</p>{tutorMeta ? <ResultSource source={tutorMeta.source} note={tutorMeta.note} fallbackReason={tutorMeta.fallbackReason} /> : null}<Link href={`/chapters/${tutor.chapterSlug}/`} className="mt-3 inline-flex min-h-9 items-center gap-1 text-xs font-semibold text-gold hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gold">Read the full chapter →</Link></div> : null}
          </div>
        </div>
      </div>
      {error ? <ErrorMessage message={error} /> : null}
    </section>
  );
}
